Speakers lists
nairobi-gophers/gophercon2024 pull request #59
Opened 2024-10-08 15:33 UTC by nutcas3

Speakers list update 
Here is the image to it
![Screenshot 2024-10-12 at 11-36-38 Nairobi Gophers](https://github.com/user-attachments/assets/83103c85-114a-47b7-830a-fa6a926d187f)

2024-10-13 20:32 UTC, spankie requested changes

2024-10-13 20:32 UTC, spankie commented on frontend/src/components/SpeakersLists.tsx
> +        companyLogoUrl: 'https://gophers.africa/assets/wordmark_primary-B6eTT4Ct.svg',
Using the same logo for two speakers. Rodney doesn't work at Partna.

2024-10-13 20:49 UTC, nutcas3 commented
![image](https://github.com/user-attachments/assets/c93a5173-b814-4213-88cb-63002336b11b)

2024-10-14 03:18 UTC, spankie approved these changes

2024-10-14 03:19 UTC, merged